namespace Daxis.Core;

public sealed record DaxFunction(string Name, string Description, string[] Parameters);

/// <summary>
/// Hard-coded registry of DAX functions with descriptions and parameter signatures.
/// Used by DAX IntelliSense completion and signature help.
/// </summary>
public static class DaxFunctions
{
    public static DaxFunction? TryGet(string name)
    {
        foreach (var f in All)
            if (string.Equals(f.Name, name, StringComparison.OrdinalIgnoreCase))
                return f;
        return null;
    }

    public static readonly IReadOnlyList<DaxFunction> All = new DaxFunction[]
    {
        // ── Aggregation ───────────────────────────────────────────────────────
        new("SUM",            "Returns the sum of all values in a column.",                      ["column"]),
        new("SUMX",           "Returns the sum of an expression evaluated for each row.",        ["table", "expression"]),
        new("AVERAGE",        "Returns the arithmetic mean of all values in a column.",          ["column"]),
        new("AVERAGEX",       "Evaluates an expression for each row and returns the mean.",      ["table", "expression"]),
        new("MIN",            "Returns the smallest value in a column.",                         ["column"]),
        new("MINA",           "Returns the smallest value including TRUE/FALSE.",                ["column"]),
        new("MINX",           "Returns the minimum value of an expression evaluated per row.",   ["table", "expression"]),
        new("MAX",            "Returns the largest value in a column.",                          ["column"]),
        new("MAXA",           "Returns the largest value including TRUE/FALSE.",                 ["column"]),
        new("MAXX",           "Returns the maximum value of an expression evaluated per row.",   ["table", "expression"]),
        new("COUNT",          "Counts the number of numeric values in a column.",                ["column"]),
        new("COUNTA",         "Counts the number of non-blank values in a column.",              ["column"]),
        new("COUNTX",         "Counts non-blank results of an expression per row.",              ["table", "expression"]),
        new("COUNTROWS",      "Counts the number of rows in a table.",                           ["table"]),
        new("COUNTBLANK",     "Counts the number of blank values in a column.",                  ["column"]),
        new("DISTINCTCOUNT",  "Counts the number of distinct values in a column.",               ["column"]),
        new("DISTINCTCOUNTNOBLANK", "Counts distinct non-blank values in a column.",             ["column"]),
        new("PRODUCT",        "Returns the product of all values in a column.",                  ["column"]),
        new("PRODUCTX",       "Returns the product of an expression evaluated for each row.",    ["table", "expression"]),
        new("MEDIAN",         "Returns the median value of a column.",                           ["column"]),
        new("MEDIANX",        "Returns the median of an expression evaluated for each row.",     ["table", "expression"]),
        new("PERCENTILE.INC", "Returns the k-th percentile (inclusive) of values in a column.", ["column", "k"]),
        new("PERCENTILE.EXC", "Returns the k-th percentile (exclusive) of values in a column.", ["column", "k"]),
        new("STDEV.P",        "Returns the standard deviation of the entire population.",        ["column"]),
        new("STDEV.S",        "Returns the standard deviation of a sample.",                     ["column"]),
        new("VAR.P",          "Returns the variance of the entire population.",                  ["column"]),
        new("VAR.S",          "Returns the variance of a sample.",                               ["column"]),

        // ── Filter / Table manipulation ───────────────────────────────────────
        new("CALCULATE",      "Evaluates an expression with modified filters.",                  ["expression", "filter1", "..."]),
        new("CALCULATETABLE", "Evaluates a table expression with modified filters.",             ["expression", "filter1", "..."]),
        new("FILTER",         "Returns a table that is a subset of another table.",              ["table", "filter_expression"]),
        new("ALL",            "Removes all filters from a table or column(s).",                  ["tableOrColumn", "..."]),
        new("ALLEXCEPT",      "Removes all filters except those on specified columns.",          ["table", "column1", "..."]),
        new("ALLSELECTED",    "Removes context filters while keeping slicer/visual filters.",    ["tableOrColumn"]),
        new("ALLNOBLANKROW",  "Returns all rows except blank rows from a table.",                ["tableOrColumn"]),
        new("VALUES",         "Returns a single-column table of distinct values.",               ["tableOrColumn"]),
        new("DISTINCT",       "Returns a single-column table of distinct values.",               ["tableOrColumn"]),
        new("DISTINCTVALUES", "Returns unique non-blank values of a column.",                    ["column"]),
        new("KEEPFILTERS",    "Modifies CALCULATE so existing filters are not removed.",         ["expression"]),
        new("REMOVEFILTERS",  "Removes filters from tables or columns.",                         ["tableOrColumn", "..."]),
        new("SELECTEDVALUE",  "Returns value if only one distinct value, else alternateResult.", ["column", "alternateResult"]),
        new("HASONEVALUE",    "Returns TRUE if column has exactly one filtered value.",          ["column"]),
        new("HASONEFILTER",   "Returns TRUE if exactly one value is directly filtered.",         ["column"]),
        new("ISFILTERED",     "Returns TRUE if column has a direct filter applied.",             ["column"]),
        new("ISCROSSFILTERED","Returns TRUE if column or related column has a filter.",          ["column"]),
        new("CROSSFILTER",    "Specifies the cross-filtering direction between two columns.",    ["leftColumn", "rightColumn", "direction"]),
        new("USERELATIONSHIP","Specifies the relationship to use in a calculation.",             ["columnName1", "columnName2"]),

        // ── Time intelligence ─────────────────────────────────────────────────
        new("TOTALYTD",            "Evaluates an expression year-to-date.",                           ["expression", "dates", "filter"]),
        new("TOTALQTD",            "Evaluates an expression quarter-to-date.",                        ["expression", "dates", "filter"]),
        new("TOTALMTD",            "Evaluates an expression month-to-date.",                          ["expression", "dates", "filter"]),
        new("DATESYTD",            "Returns a table of dates from the start of the year.",            ["dates", "year_end_date"]),
        new("DATESQTD",            "Returns a table of dates from the start of the quarter.",         ["dates"]),
        new("DATESMTD",            "Returns a table of dates from the start of the month.",           ["dates"]),
        new("SAMEPERIODLASTYEAR",  "Returns dates shifted back one year.",                            ["dates"]),
        new("DATEADD",             "Shifts a set of dates by a specified interval.",                  ["dates", "number_of_intervals", "interval"]),
        new("DATESBETWEEN",        "Returns dates between start_date and end_date.",                  ["dates", "start_date", "end_date"]),
        new("DATESINPERIOD",       "Returns dates starting at start_date for the given interval.",    ["dates", "start_date", "number_of_intervals", "interval"]),
        new("PARALLELPERIOD",      "Returns a parallel period shifted by intervals.",                 ["dates", "number_of_intervals", "interval"]),
        new("PREVIOUSYEAR",        "Returns dates for the previous year.",                            ["dates", "year_end_date"]),
        new("PREVIOUSQUARTER",     "Returns dates for the previous quarter.",                         ["dates"]),
        new("PREVIOUSMONTH",       "Returns dates for the previous month.",                           ["dates"]),
        new("PREVIOUSDAY",         "Returns dates for the previous day.",                             ["dates"]),
        new("NEXTYEAR",            "Returns dates for the next year.",                                ["dates", "year_end_date"]),
        new("NEXTQUARTER",         "Returns dates for the next quarter.",                             ["dates"]),
        new("NEXTMONTH",           "Returns dates for the next month.",                               ["dates"]),
        new("NEXTDAY",             "Returns dates for the next day.",                                 ["dates"]),
        new("FIRSTDATE",           "Returns the first date in a column.",                             ["dates"]),
        new("LASTDATE",            "Returns the last date in a column.",                              ["dates"]),
        new("STARTOFYEAR",         "Returns the first date of the year.",                             ["dates", "year_end_date"]),
        new("STARTOFQUARTER",      "Returns the first date of the quarter.",                          ["dates"]),
        new("STARTOFMONTH",        "Returns the first date of the month.",                            ["dates"]),
        new("ENDOFYEAR",           "Returns the last date of the year.",                              ["dates", "year_end_date"]),
        new("ENDOFQUARTER",        "Returns the last date of the quarter.",                           ["dates"]),
        new("ENDOFMONTH",          "Returns the last date of the month.",                             ["dates"]),
        new("OPENINGBALANCEYEAR",  "Evaluates expression at the start of the year.",                  ["expression", "dates", "filter"]),
        new("OPENINGBALANCEQUARTER","Evaluates expression at the start of the quarter.",              ["expression", "dates", "filter"]),
        new("OPENINGBALANCEMONTH", "Evaluates expression at the start of the month.",                 ["expression", "dates", "filter"]),
        new("CLOSINGBALANCEYEAR",  "Evaluates expression at the end of the year.",                    ["expression", "dates", "filter"]),
        new("CLOSINGBALANCEQUARTER","Evaluates expression at the end of the quarter.",                ["expression", "dates", "filter"]),
        new("CLOSINGBALANCEMONTH", "Evaluates expression at the end of the month.",                   ["expression", "dates", "filter"]),
        new("CALENDARAUTO",        "Generates a calendar table from min/max dates in the model.",     ["fiscal_year_end_month"]),
        new("CALENDAR",            "Returns a table of dates between start_date and end_date.",       ["start_date", "end_date"]),

        // ── Logical ───────────────────────────────────────────────────────────
        new("IF",       "Returns one value if condition is TRUE, another if FALSE.",   ["logical_test", "value_if_true", "value_if_false"]),
        new("IFERROR",  "Returns value; if error, returns value_if_error.",            ["value", "value_if_error"]),
        new("SWITCH",   "Evaluates an expression against a list of values.",          ["expression", "value1", "result1", "...", "else"]),
        new("AND",      "Returns TRUE if both arguments are TRUE.",                    ["logical1", "logical2"]),
        new("OR",       "Returns TRUE if any argument is TRUE.",                       ["logical1", "logical2"]),
        new("NOT",      "Reverses the logical value of its argument.",                 ["logical"]),
        new("TRUE",     "Returns the logical value TRUE.",                             []),
        new("FALSE",    "Returns the logical value FALSE.",                            []),
        new("COALESCE", "Returns the first non-blank expression.",                     ["expression1", "expression2", "..."]),

        // ── Text ──────────────────────────────────────────────────────────────
        new("CONCATENATE",       "Joins two text strings into one.",                             ["text1", "text2"]),
        new("CONCATENATEX",      "Concatenates the result of an expression evaluated per row.",  ["table", "expression", "delimiter"]),
        new("LEFT",              "Returns the leftmost n characters of a string.",               ["text", "num_chars"]),
        new("RIGHT",             "Returns the rightmost n characters of a string.",              ["text", "num_chars"]),
        new("MID",               "Returns characters from the middle of a string.",              ["text", "start_num", "num_chars"]),
        new("LEN",               "Returns the number of characters in a string.",               ["text"]),
        new("UPPER",             "Converts a string to uppercase.",                              ["text"]),
        new("LOWER",             "Converts a string to lowercase.",                              ["text"]),
        new("TRIM",              "Removes extra spaces from a string.",                          ["text"]),
        new("SUBSTITUTE",        "Replaces occurrences of a substring with another string.",     ["text", "old_text", "new_text", "instance_num"]),
        new("REPLACE",           "Replaces part of a string with a different string.",          ["old_text", "start_num", "num_chars", "new_text"]),
        new("FIND",              "Finds the starting position of a substring (case-sensitive).", ["find_text", "within_text", "start_num"]),
        new("SEARCH",            "Finds the starting position of a substring (case-insensitive).", ["find_text", "within_text", "start_num"]),
        new("EXACT",             "Checks whether two strings are identical (case-sensitive).",   ["text1", "text2"]),
        new("FIXED",             "Formats a number as text with a specified number of decimals.", ["number", "decimals", "no_commas"]),
        new("FORMAT",            "Converts a value to text in a specified format.",              ["value", "format_string"]),
        new("VALUE",             "Converts a text string to a number.",                          ["text"]),
        new("TEXT",              "Converts a value to text using a format.",                     ["value", "format_string"]),
        new("REPT",              "Repeats a text string a specified number of times.",           ["text", "num_times"]),
        new("UNICHAR",           "Returns the character specified by a Unicode code.",           ["number"]),
        new("UNICODE",           "Returns the Unicode code point of the first character.",       ["text"]),
        new("STARTSWITH",        "Returns TRUE if a string starts with the specified prefix.",   ["text", "prefix"]),
        new("CONTAINSSTRING",    "Returns TRUE if a string contains another string.",            ["within_text", "find_text"]),
        new("CONTAINSSTRINGEXACT","Returns TRUE if a string contains another (case-sensitive).", ["within_text", "find_text"]),

        // ── Math / numeric ───────────────────────────────────────────────────
        new("ABS",        "Returns the absolute value of a number.",                             ["number"]),
        new("CEILING",    "Rounds a number up to the nearest multiple of significance.",         ["number", "significance"]),
        new("FLOOR",      "Rounds a number down to the nearest multiple of significance.",       ["number", "significance"]),
        new("ROUND",      "Rounds a number to the specified number of digits.",                  ["number", "num_digits"]),
        new("ROUNDUP",    "Rounds a number away from zero.",                                     ["number", "num_digits"]),
        new("ROUNDDOWN",  "Rounds a number towards zero.",                                       ["number", "num_digits"]),
        new("INT",        "Rounds a number down to the nearest integer.",                        ["number"]),
        new("TRUNC",      "Truncates a number to an integer by removing the decimal.",           ["number", "num_digits"]),
        new("MOD",        "Returns the remainder after division.",                               ["number", "divisor"]),
        new("QUOTIENT",   "Returns the integer portion of a division.",                          ["numerator", "denominator"]),
        new("POWER",      "Returns a number raised to a power.",                                 ["number", "power"]),
        new("SQRT",       "Returns the square root of a number.",                                ["number"]),
        new("EXP",        "Returns e raised to the power of a number.",                          ["number"]),
        new("LN",         "Returns the natural logarithm of a number.",                          ["number"]),
        new("LOG",        "Returns the logarithm of a number to the specified base.",            ["number", "base"]),
        new("LOG10",      "Returns the base-10 logarithm of a number.",                          ["number"]),
        new("SIGN",       "Returns the sign of a number: 1, 0, or -1.",                         ["number"]),
        new("ODD",        "Rounds a number up to the nearest odd integer.",                      ["number"]),
        new("EVEN",       "Rounds a number up to the nearest even integer.",                     ["number"]),
        new("DIVIDE",     "Divides numerator by denominator; returns AlternateResult if 0.",     ["numerator", "denominator", "alternateResult"]),
        new("RAND",       "Returns a random number between 0 and 1.",                            []),
        new("RANDBETWEEN","Returns a random integer between two numbers.",                       ["bottom", "top"]),
        new("MROUND",     "Rounds a number to the desired multiple.",                            ["number", "multiple"]),
        new("ISO.CEILING","Rounds a number up to the nearest integer.",                          ["number", "significance"]),
        new("COMBIN",     "Returns the number of combinations for a given number of items.",     ["number", "number_chosen"]),
        new("COMBINA",    "Returns the number of combinations (with repetitions).",              ["number", "number_chosen"]),
        new("PERMUT",     "Returns the number of permutations for a given number.",              ["number", "number_chosen"]),
        new("GCD",        "Returns the greatest common divisor.",                                ["number1", "number2"]),
        new("LCM",        "Returns the least common multiple.",                                  ["number1", "number2"]),
        new("PI",         "Returns the value of pi (3.14159...).",                               []),
        new("FACT",       "Returns the factorial of a number.",                                  ["number"]),

        // ── Date / Time ──────────────────────────────────────────────────────
        new("DATE",            "Returns the date given year, month, and day.",                   ["year", "month", "day"]),
        new("TIME",            "Returns the time given hour, minute, and second.",               ["hour", "minute", "second"]),
        new("NOW",             "Returns the current date and time.",                             []),
        new("TODAY",           "Returns today's date.",                                          []),
        new("YEAR",            "Returns the year of a date.",                                    ["date"]),
        new("QUARTER",         "Returns the quarter (1-4) of a date.",                          ["date"]),
        new("MONTH",           "Returns the month (1-12) of a date.",                           ["date"]),
        new("DAY",             "Returns the day of the month (1-31) of a date.",                ["date"]),
        new("HOUR",            "Returns the hour (0-23) of a time value.",                       ["datetime"]),
        new("MINUTE",          "Returns the minute (0-59) of a time value.",                    ["datetime"]),
        new("SECOND",          "Returns the second (0-59) of a time value.",                    ["datetime"]),
        new("WEEKDAY",         "Returns the day of the week as a number.",                       ["date", "return_type"]),
        new("WEEKNUM",         "Returns the week number of a date.",                             ["date", "return_type"]),
        new("DATEDIFF",        "Returns the count of intervals between two dates.",              ["start_date", "end_date", "interval"]),
        new("EDATE",           "Returns the date that is n months from start_date.",             ["start_date", "months"]),
        new("EOMONTH",         "Returns the last day of the month n months from start_date.",    ["start_date", "months"]),
        new("DATEVALUE",       "Converts a date in text format to a date.",                      ["date_text"]),
        new("TIMEVALUE",       "Converts a time in text format to a time.",                      ["time_text"]),
        new("NETWORKDAYS",     "Returns the number of working days between two dates.",          ["start_date", "end_date", "holidays"]),
        new("WORKDAY",         "Returns the date after a given number of working days.",         ["start_date", "days", "holidays"]),

        // ── Relationship / lookup ─────────────────────────────────────────────
        new("RELATED",        "Returns a related value from another table.",                     ["column"]),
        new("RELATEDTABLE",   "Returns a table of related rows from another table.",             ["table"]),
        new("LOOKUPVALUE",    "Returns a value from a column matching search criteria.",         ["result_column", "search_column", "search_value", "..."]),

        // ── Table constructors / manipulation ─────────────────────────────────
        new("SUMMARIZE",          "Returns a summary table with grouped rows.",                        ["table", "groupBy_column", "...", "name", "expression"]),
        new("SUMMARIZECOLUMNS",   "Groups by columns and aggregates with measures.",                   ["groupBy_column", "...", "name", "expression"]),
        new("ADDCOLUMNS",         "Adds calculated columns to a table expression.",                    ["table", "name", "expression", "..."]),
        new("SELECTCOLUMNS",      "Returns a table with only selected columns (and expressions).",     ["table", "name", "expression", "..."]),
        new("UNION",              "Returns a table that is the union of two tables.",                  ["table1", "table2", "..."]),
        new("INTERSECT",          "Returns the row intersection of two tables.",                       ["left_table", "right_table"]),
        new("EXCEPT",             "Returns rows from left table not appearing in the right table.",    ["left_table", "right_table"]),
        new("NATURALLEFTOUTERJOIN","Joins two tables using the left outer join semantics.",            ["left_table", "right_table"]),
        new("NATURALINNERJOIN",   "Joins two tables using the inner join semantics.",                  ["left_table", "right_table"]),
        new("CROSSJOIN",          "Returns a table with the Cartesian product of two tables.",         ["table1", "table2", "..."]),
        new("GENERATE",           "Returns the Cartesian product filtered by a correlated table.",     ["table1", "table2"]),
        new("GENERATEALL",        "Returns the Cartesian product including blank rows.",               ["table1", "table2"]),
        new("ROW",                "Returns a single-row table with named columns.",                    ["name", "expression", "..."]),
        new("DATATABLE",          "Returns a table with defined columns and values.",                  ["column_name", "column_type", "data"]),
        new("TOPN",               "Returns the top N rows of a table ordered by an expression.",       ["n_value", "table", "orderBy_expression", "..."]),
        new("TOPNSKIP",           "Returns the top N rows after skipping the first M rows.",           ["n_value", "skip_value", "table", "orderBy_expression", "..."]),
        new("SAMPLE",             "Returns a random sample of rows from a table.",                     ["n_value", "table", "orderBy_expression"]),
        new("RANKX",              "Returns the rank of a value in a list of values.",                  ["table", "expression", "value", "order", "ties"]),

        // ── Information / type checking ───────────────────────────────────────
        new("ISBLANK",         "Returns TRUE if a value is blank.",                              ["value"]),
        new("ISERROR",         "Returns TRUE if a value is an error.",                           ["value"]),
        new("ISLOGICAL",       "Returns TRUE if a value is a logical (TRUE/FALSE).",             ["value"]),
        new("ISNUMBER",        "Returns TRUE if a value is a number.",                           ["value"]),
        new("ISTEXT",          "Returns TRUE if a value is text.",                               ["value"]),
        new("ISNONTEXT",       "Returns TRUE if a value is not text (or blank).",                ["value"]),
        new("ISINSCOPE",       "Returns TRUE if the column is in the current level of hierarchy.", ["column"]),
        new("ISEMPTY",         "Returns TRUE if a table is empty.",                              ["table"]),
        new("CONTAINS",        "Returns TRUE if a table contains rows matching criteria.",       ["table", "column1", "value1", "..."]),
        new("CONTAINSROW",     "Returns TRUE if a row exists in a table.",                       ["table", "value1", "..."]),
        new("CUSTOMDATA",      "Returns the content of the CustomData connection string.",       []),
        new("USERNAME",        "Returns the current username.",                                  []),
        new("USERPRINCIPALNAME","Returns the user principal name (UPN) of the current user.",   []),
        new("USEROBJECTID",    "Returns the Microsoft Entra Object ID of the current user.",     []),

        // ── Statistical ──────────────────────────────────────────────────────
        new("NORM.DIST",    "Returns the normal distribution for a given mean and std dev.",     ["x", "mean", "standard_dev", "cumulative"]),
        new("NORM.INV",     "Returns the inverse of the normal distribution.",                   ["probability", "mean", "standard_dev"]),
        new("NORM.S.DIST",  "Returns the standard normal distribution.",                         ["z", "cumulative"]),
        new("NORM.S.INV",   "Returns the inverse of the standard normal distribution.",          ["probability"]),
        new("T.DIST",       "Returns the t-distribution.",                                       ["x", "deg_freedom", "cumulative"]),
        new("T.DIST.2T",    "Returns the two-tailed student's t-distribution.",                 ["x", "deg_freedom"]),
        new("T.DIST.RT",    "Returns the right-tailed student's t-distribution.",               ["x", "deg_freedom"]),
        new("T.INV",        "Returns the left-tailed inverse of the student's t-distribution.", ["probability", "deg_freedom"]),
        new("T.INV.2T",     "Returns the two-tailed inverse of the student's t-distribution.", ["probability", "deg_freedom"]),
        new("BETA.DIST",    "Returns the beta cumulative distribution function.",                ["x", "alpha", "beta", "cumulative", "A", "B"]),
        new("BETA.INV",     "Returns the inverse of the beta cumulative distribution.",          ["probability", "alpha", "beta", "A", "B"]),
        new("CHISQ.DIST",   "Returns the chi-squared distribution.",                             ["x", "deg_freedom", "cumulative"]),
        new("CHISQ.DIST.RT","Returns the right-tail probability of chi-squared distribution.",  ["x", "deg_freedom"]),
        new("CHISQ.INV",    "Returns the inverse of chi-squared distribution.",                  ["probability", "deg_freedom"]),
        new("CHISQ.INV.RT", "Returns the right-tail inverse of chi-squared distribution.",      ["probability", "deg_freedom"]),
        new("F.DIST",       "Returns the F probability distribution.",                           ["x", "deg_freedom1", "deg_freedom2", "cumulative"]),
        new("F.DIST.RT",    "Returns the right-tailed F probability distribution.",             ["x", "deg_freedom1", "deg_freedom2"]),
        new("F.INV",        "Returns the inverse of the F probability distribution.",            ["probability", "deg_freedom1", "deg_freedom2"]),
        new("F.INV.RT",     "Returns the right-tailed inverse of F probability distribution.",  ["probability", "deg_freedom1", "deg_freedom2"]),
        new("CORR",         "Returns the correlation coefficient between two columns.",          ["column1", "column2"]),
        new("COVAR.P",      "Returns population covariance.",                                    ["column1", "column2"]),
        new("COVAR.S",      "Returns sample covariance.",                                        ["column1", "column2"]),
        new("LINEST",       "Returns statistics for a straight line fitting data.",              ["known_y", "known_x", "const", "stats"]),
        new("LINESTX",      "Returns statistics for a straight line fitting expression data.",   ["table", "known_y_expression", "known_x_expression"]),
        new("FORECAST",     "Returns a value along a linear trend.",                             ["x", "values_y", "values_x"]),
        new("XIRR",         "Returns the internal rate of return for a schedule of cash flows.", ["table", "values", "dates", "guess"]),
        new("XNPV",         "Returns the net present value for a schedule of cash flows.",       ["rate", "table", "values", "dates"]),

        // ── Iteration / variable ─────────────────────────────────────────────
        new("EARLIER",      "Returns the current value of a column in an outer evaluation.",    ["column", "num"]),
        new("EARLIEST",     "Returns the current value of a column in the outermost eval.",     ["column"]),
        new("NAMEOF",       "Returns the name of an object as a string.",                        ["object"]),

        // ── Financial ────────────────────────────────────────────────────────
        new("DB",       "Returns the depreciation of an asset using fixed-declining method.",    ["cost", "salvage", "life", "period", "month"]),
        new("DDB",      "Returns the depreciation using double-declining method.",               ["cost", "salvage", "life", "period", "factor"]),
        new("FV",       "Returns the future value of an investment.",                            ["rate", "nper", "pmt", "pv", "type"]),
        new("IPMT",     "Returns the interest payment for a given period.",                      ["rate", "per", "nper", "pv", "fv", "type"]),
        new("IRR",      "Returns the internal rate of return for a series of cash flows.",       ["values", "guess"]),
        new("NPER",     "Returns the number of periods for an investment.",                      ["rate", "pmt", "pv", "fv", "type"]),
        new("NPV",      "Returns the net present value of an investment.",                       ["rate", "value1", "value2", "..."]),
        new("PMT",      "Returns the periodic payment for an annuity.",                          ["rate", "nper", "pv", "fv", "type"]),
        new("PPMT",     "Returns the principal payment for a given period.",                     ["rate", "per", "nper", "pv", "fv", "type"]),
        new("PV",       "Returns the present value of an investment.",                           ["rate", "nper", "pmt", "fv", "type"]),
        new("RATE",     "Returns the interest rate per period of an annuity.",                   ["nper", "pmt", "pv", "fv", "type", "guess"]),
        new("SLN",      "Returns the straight-line depreciation of an asset.",                   ["cost", "salvage", "life"]),
        new("SYD",      "Returns the sum-of-years' digits depreciation.",                        ["cost", "salvage", "life", "per"]),
    };
}
